apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodereceiver
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "nodereceiver"
        dapr.io/port: "8088"
  spec:
    containers:
      - name: node
        image: cevheri/nodejs-receiver-example
        ports:
          - containerPort: 8088
        imagePullPolicy: Always

# kubectl apply -f ./app.yaml
# kubectl logs nodereceiver-<postfix local pod_id> node
# Receiver is running on port 8088
#   { msg: ’Hello, World! 2’ }
#   { msg: ’Hello, World! 3’ }
#   { msg: ’Hello, World! 4’ }
#   { msg: ’Hello, World! 5’ }
#   { msg: ’Hello, World! 6’ }
